# Generated by Django 3.2.9 on 2022-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity_sold',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='total_sales_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
